export const AUDIT_ACTIONS = [
  // User / account
  'USER_REGISTERED',
  'USER_DEACTIVATED',
  'USER_REACTIVATED',
  'USER_PASSWORD_CHANGED',
  'USER_SESSIONS_REVOKED',
  'USER_PASSWORD_RESET_ISSUED',
  'USER_PASSWORD_RESET_REDEEMED',
  'USER_PROMOTED_TO_ADMIN',
  'USER_DEMOTED_FROM_ADMIN',
  'USER_PROMOTED_TO_SUPER_ADMIN',
  'SUPER_ADMIN_SEEDED',
  'ADMIN_SESSIONS_REVOKED',
  'SESSION_REUSE_DETECTED',
  'ACCOUNT_LOCKOUT_ESCALATED',

  // Car
  'CAR_SUBMITTED',
  'CAR_APPROVED',
  'CAR_REJECTED',
  'CAR_PUBLISHED',
  'CAR_DELISTED',
  'CAR_DELISTED_FORCED',

  // Booking
  'BOOKING_REQUESTED',
  'BOOKING_CONFIRMED',
  'BOOKING_REJECTED',
  'BOOKING_STARTED',
  'BOOKING_STARTED_IDENTITY_MISMATCH',
  'BOOKING_ACTIVATED_UNPAID',
  'BOOKING_COMPLETED',
  'BOOKING_TERMINATED',
  'BOOKING_CANCELLED',
  'BOOKING_CANCELLATION_REQUESTED',
  'BOOKING_CANCELLATION_DENIED',
  'BOOKING_NO_SHOW',
  'BOOKING_NO_SHOW_CLEARED',
  'BOOKING_HANDOVER_REFUSED',
  'BOOKING_HANDOVER_REFUSED_CANCELLED',

  // Payment
  'PAYMENT_RECORDED',
  'PAYMENT_SETTLED',
  'PAYMENT_VOIDED',
  'PAYMENT_REFUNDED',
  'DEPOSIT_RETAINED',

  // System / superadmin
  'SYSTEM_CONFIG_CHANGED',
] as const;
export type AuditAction = (typeof AUDIT_ACTIONS)[number];
